### users.getAll
GET http://localhost:8080/users
X-Login: vasya
X-Password: password

### users.getById
GET http://localhost:8080/users/1
X-Login: vasya
X-Password: password

### users.create
POST http://localhost:8080/users
X-Login: vasya
X-Password: password
Content-Type: application/json

{
  "id": 0,
  "login": "vanya",
  "password": "password",
  "roles": ["ROLE_USER"]
}

### users.update
PUT http://localhost:8080/users
X-Login: vasya
X-Password: password
Content-Type: application/json

{
  "id": 3,
  "login": "vanya",
  "password": "top-password",
  "roles": ["ROLE_USER", "ROLE_ADMIN"]
}

### users.deleteById
DELETE http://localhost:8080/users/2
X-Login: vasya
X-Password: password

### posts.getAll
GET http://localhost:8080/posts
X-Login: vasya
X-Password: password

### posts.getById
GET http://localhost:8080/posts/1
X-Login: vasya
X-Password: password

### posts.create
POST http://localhost:8080/posts
X-Login: vasya
X-Password: password
Content-Type: application/json

{
  "id": 0,
  "content": "Demo Post",
  "tags": ["demo", "fun"],
  "geo": {
    "lat": 55.00,
    "lng": 45.00
  }
}

### posts.update
PUT http://localhost:8080/posts
X-Login: vasya
X-Password: password
Content-Type: application/json

{
  "id": 2,
  "content": "Demo Post (updated)",
  "tags": ["demo", "fun"],
  "geo": {
    "lat": 55.00,
    "lng": 45.00
  }
}

### posts.deleteById
DELETE http://localhost:8080/posts/2
X-Login: vasya
X-Password: password
